version: 7.0.{build}
clone_depth: 1
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    node -v

    npm -v
before_build:
- ps: dotnet restore
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
after_test:
- ps: >-

    $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

    Write-Host $PostBuildTests

    & "$PostBuildTests"

    $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

    Write-Host $PostBuildPackArtifacts

    & "$PostBuildPackArtifacts"

deploy:
- provider: GitHub
  auth_token:
    secure: wRgB5QjivzfFUONQx/GEZHusulU1CTg3GhOJrpav5XR2tSJGtpgZo1M8CIUW2dwjuO0EvrcBySRAi0HltlyMIZQMQnTwBFCLi+zB/2zg1IA=
  repository: IsraelHikingMap/Site
  draft: true
