version: 6.0.{build}
clone_depth: 1
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    Install-Product node 8.9

    node -v

    npm -v

    npm install -g npm@5.2.0 --loglevel=error

before_build:
- ps: dotnet restore
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
after_test:
- ps: >-
    npm run-script lint

    $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

    Write-Host $PostBuildTests

    & "$PostBuildTests"

    $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

    Write-Host $PostBuildPackArtifacts

    & "$PostBuildPackArtifacts"
