version: 8.5.{build}
clone_depth: 3
configuration: Release
environment:
  matrix:
    - PRODUCT: web
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PRODUCT: android
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      STORE_PASSWORD:
        secure: ZF3GiQxQ98B1HGKZOwlnmris5yN68mvx3UF6TVsnpws=
      PASSWORD:
        secure: mqbXr4+cn3l9YNyKhOezbA==
    - PRODUCT: ios
      APPVEYOR_BUILD_WORKER_IMAGE: macOS
install:
- ps: >-
    Install-Product node 10.15

    npm install -g npm@6.9.0 --loglevel=error

    npm install -g increase-memory-limit
        
    node --version

    npm --version
for:
  -
    matrix:
      only: 
        - PRODUCT: web
    before_build:
      - ps: dotnet restore
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: $(appveyor_build_version)
      package_version: $(appveyor_build_version)
      assembly_version: $(appveyor_build_version)
      file_version: $(appveyor_build_version)
      informational_version: $(appveyor_build_version)
    build:
      project: IsraelHiking.sln
      parallel: true
      verbosity: minimal
    test: off
    after_test:
      - ps: >-
            $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

            Write-Host $PostBuildTests

            & "$PostBuildTests"

            $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

            Write-Host $PostBuildPackArtifacts

            & "$PostBuildPackArtifacts"

  -
    matrix:
      only:
        - PRODUCT: android
    before_build:
    - ps: >-
        choco install gradle --version 4.9 --no-progress

        $env:Path += ";C:\ProgramData\chocolatey\lib\gradle\tools\gradle-4.9\bin;$env:ANDROID_HOME\tools\bin\;C:\Program Files\Git\mingw64\libexec\git-core"

        gradle --version

        for($i=0;$i -lt 30;$i++) { $response += "y`n"};

        Invoke-Expression """$response"" | sdkmanager.bat --licenses"

        Invoke-Expression """$response"" | sdkmanager.bat --update | out-null"

        Invoke-Expression "sdkmanager.bat ""platform-tools"" ""tools"" ""platforms;android-26"" ""build-tools;28.0.2"" ""extras;google;m2repository"" | out-null"

    build: off
    test: off
    after_test:
    - ps: >-
        $BuildAndPublishAndroid = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishAndroid.ps1"

        Write-Host $BuildAndPublishAndroid

        & "$BuildAndPublishAndroid"

  -
    matrix:
      only:
        - PRODUCT: ios
    build: off
    test: off

deploy:
- provider: GitHub
  auth_token:
    secure: UhPMkdOfJ0iYk+ZEJapaimnlsy+yXWXYzwJ7Lgj9aiMq2lj5JcUkN1UI0Q9QZru6
  repository: IsraelHikingMap/Site
  draft: true
  on:
    appveyor_repo_tag: true
