version: 7.1.{build}
clone_depth: 1
image: Visual Studio 2017
configuration: Release
environment:
  ANDROID_HOME: C:\android-sdk-windows
install:
- ps: >-
    npm install -g npm@6.2.0 --loglevel=error

    node -v

    npm -v

    appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip

    $env:ANDROID_HOME="$env:APPVEYOR_BUILD_FOLDER\android"

    #Invoke-Expression "7z x sdk-tools-windows-4333796.zip -o$env:ANDROID_HOME"

    #Invoke-Expression "yes | $env:ANDROID_HOME\tools\bin\sdkmanager.bat --licenses"
before_build:
- ps: dotnet restore
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
after_test:
- ps: >-

    $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

    Write-Host $PostBuildTests

    & "$PostBuildTests"

    $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

    Write-Host $PostBuildPackArtifacts

    & "$PostBuildPackArtifacts"

deploy:
- provider: GitHub
  auth_token:
    secure: UhPMkdOfJ0iYk+ZEJapaimnlsy+yXWXYzwJ7Lgj9aiMq2lj5JcUkN1UI0Q9QZru6
  repository: IsraelHikingMap/Site
  draft: true
  on:
    appveyor_repo_tag: true
