version: 9.8.{build}
clone_depth: 3
configuration: Release
skip_branch_with_pr: true
environment:
  STORE_PASSWORD:
    secure: ZF3GiQxQ98B1HGKZOwlnmris5yN68mvx3UF6TVsnpws=
  PASSWORD:
    secure: mqbXr4+cn3l9YNyKhOezbA==
  matrix:
  #  - PRODUCT: web
  #    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - PRODUCT: android
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
      ANDROID_SDK_ROOT: C:\Program Files (x86)\Android\android-sdk
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      PLAYSTORE_JSON:
        secure: im6vOib/yTGRkCIm9ai8sBWV9LG1I+lCrz5N2IKPLE5ZspmciN9CVlBMKfbWW6M5qSqif1ozvPYeSkJLaLMT7/4UboHq+9qIUNQL+pRLlE0fVmQGC3jrJE1QBWQbCQ6kh586ppUB3nWo+BAdAiiTwWBca04KHTK1KTXQuL5j95KHFnyIe/IOhla1yKKq/jXNYwesdHCEras0zjR7MErKfwD9/yxfpyNzlaywYz6TrSMEZgi32zPScYLu0/RIxnVRAqKWVV8XK5nKeCNs+JKcBSHX4ussrq6NaLAdKbi5B6LaEy5EsYEqLr/DIqBjTQa1sT4b+IV8jwwmxOuVy8GUYNWFiYI/F5/jbyZfg/V58FKhTN+1cyV+y6qepHdMnZ3mzMmzMBCm5EsIBz2l4wlAqmK4zJJor5QS5wFqYWNYaseI82G4Ztj2DXZu7YQYwepr0GoXBwaZ/g78dFOd+s8h8UNZazUtIEygS1reGZcgE1sA11sbRvgUUqS91WbASafSNbxu4rrIDTX9yUhWrkerJcbX7Ue2BFi9LTtuFhNs5j0rzizb9KArfyd+UIRzBRPg+u6VCCTQx3SGLYZqvXpTW6VZGGTM3n2ZN/UiSIH/o/LBpRl2c90sXz65Ny4aJsiyd+Bmp0SQVoptbMjvxWbt4XI0uo6YOh2vSDQKD8AAkn797aU2nuj96FE89Ntf2ZJa+mxymU9XBYkEbqho7BGYpxTl1oR+goC8MdoffSa+kWCKJpEVNWIMI8q1uXrDwLyJCo3zShRmJe88Pl+NZdo+tQZw2QALBzrtOPBBS2JDkqnhNrpyNEYoegphtlWS+fpN/MIpwXG/kbTyqXAJTyciZ9MPbn9QeAuwBbPD6yFTloUtcux4VwnEbfQfK0HdyvicEoD7ltMbkBbHHu/0yHNPC6XmnM8h3TAmP2YU153wrfcLB/q6WYhwHCnksEpciIkPJZQk29sjR6Ks6Wlv6AeYlNUR8G2cuvO0AJWSjh2avsldKiQtn0jvebhrE7gW06cp/8HK64j/wJ9Hq7ZTRbo+afG/ijPB6b31T5LUbDY+fMUIOg1SceLQXpRc2GD/JFMpWUntyEwV6g7vojHqXElZxlELEakEmPGbWW6AecIynaLQSX7mDyPfa6Fx3CreZ9OrMbxjpUz389B2vBbHIIgBfYaErxjTiDIkjJZc+FF8sycCS2FwgUx7Ta7JYzB5IL8vNin3MLl6t3PfVDNsTkO3ixpuGL1OUGZuv3zzYOMIXt4MzDKl/hYNehOXTua5V6PMgo+rXyPzdQzjPCWHEyu0q4eRK0el6BDgQyQtSj29eMdi/oE8THCVKUoGosgYvfRqqKjrsJhsWF0ROSBcjS8Qu4Rbtgh7pu2jw5BGz15iB785zj8PvUMOAOItB8ggZXKdaoMbAdXs+pHakqW/qcBuPt8f0AlLI3Fd4lrIKI//Sn2qevoRbdcAyjjlRliutlareCT/Xhv9ia89tml4FxKURItEfqR636EcjTaUyB1MBWgErRW10RstvKQm05vVdgqJDOm8o+0+ZJEFdJBfVMgXDGejabhyKL7xUrnfyDgRdFzZTJbZ6QG0m/GzmWwbVYkxZ7Hx7pT1wAGGTbE0tiSQKcG2qEkG+XIqCxoQqcM/m7hU6DfSzbNOiC7xjW6/6GroyGxLKSZR8R9saiOnubKknWgpmk1NfXihtIhSgYJBXYh+qB8zUf5K6Qu/QNE36R6fFWnhHpEAbRn9UBmWBoNR7oPl+rR/2R90Ff69ADWDn9ak8rwoF3voIZk9VF3nDt3VMR3tyVVj2oFQl1MlbpqyjkvYN03QfOWIE4DaeBCJ/dYSdLfdJstzGQj4tu05VfJYA76p5BZ5Dd04Ofz23WZ+eJaMcKUO5nV7ZLcrpqg23tP8vyYiJ50KufQGW35l1FGARlTPXq4QxFHJcMPko8ur8XLR42nAcjG+AGjDz1S/apqL82T/KlsRYobCmc5Sz77DBxDOzyiC1jye6/k4a5w8u9NZc2k5YJseLJsBfsi/Du/FLDTdPYI6tCn4kpbRmixOQQWxpos6COD13FgS0/BzFQkzEwB89h1u3qCcmYzyy4qN3q9jTNb1DQCp54kUOPYp/ycM/adhBMVE/Mh1/MH1RbOIwHAG/JCrEh+LpWV9aYfP+Mgr1iBAcgtx2uIzSyNfEW9LqLzWgmMG2V5Zn9LN1GAZMbEXHCMnw1EZDEfxM9Mh+sEOjjWpEboYM+svsTMoSAnE/w6zNfI/QcNAa/ptosD7QBFsGTG9NT6HMu2DW2LyBfjg0/l9YE1H1lPYu71oq6HibPl1vGnBbuduGkuTOhhu/NJ3IIwcZ7uSVgQ87rsCgk5NMjBn2GPHpgypjcjLN+urXbp1RBFyXSrourMBxeDMBVzetTm366iVDWbYBFsul4mPa6lUBxPzWiZGBpdiVWIFdTko9LoF0H1ygGY247G4IQ4DwzzBo/OyFfJPpJ3RDiVlTdfwaVXIiUVoFJXgbu5GYxgcb8M4/4+NG2EJSNXjFISMcmyxgKYH5Ln6lHKJVmLdakoh53iW4e0W/uqRuFPpJIEhulj1C96z7fQUspfT+iNvUbM3odZDxZhl9cm5r6TCvWwClHL0I6788rdfsvuYaDKkF7TdzM8hwGK+IxtBC/7dT4Hjcegw75YFDTV14Z8z6/z+FIEUtusigNWmlcXYzHQlcIZiEAWK1/2IRW2cK/g+dI8DsNjsGGcdM1cikp3MfZXgc0EwbygVVgZjb4zRGh2DuI6gIv29IBnQ3x6YoZRm0qyDpqXoXedhQuwqcjoTGr3rH4mZONAlBAlMhDqFo13WmWvi+6oLUk+4ekI7jtLvtR2/FDh7lwTZ0SSINYRrZZkytP5mLGp9nVCuLc1p2yi1HTUER9ZbiU26wT5i/4yHvqhqoXw3SQoTPb1WBIuxAtSGH3yyQXoq7oQQT2LQVMK1by2QZOiWIKXjSGVWb/vDuOG+IYDezhoQKPzxMWLyYF7JibnlRwfh8rfFGOouUE3m4l9z9hXraAqt53+5oLTUkZg3N20ymmRE78IEhZJQzbQKXNUubbHv7Uv4HZ9Vgl1HigVUuBYCM+97qQZCLz+PfiOVaJ+5lBwb5nEL42NKFTCthDBdrJxYckom9VSQooaqDMI8Qw14/VqrFg==
  #  - PRODUCT: ios
  #    APPVEYOR_BUILD_WORKER_IMAGE: macOS
  #    TMS_USER: israelhikingmap@gmail.com
  #    TMS_APPLE_APPLICATION_SPECIFIC_PASSWORD:
  #      secure: oSccSp70X/744XBpfRV4UVJZKxN1jMYHxn3OHFsTSVE=
    
for:
  -
    matrix:
      only: 
        - PRODUCT: web
    install:
      - sh: nvm install 12.18
    before_build:
      - ps: dotnet restore
    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: $(appveyor_build_version)
      package_version: $(appveyor_build_version)
      assembly_version: $(appveyor_build_version)
      file_version: $(appveyor_build_version)
      informational_version: $(appveyor_build_version)
    build:
      project: IsraelHiking.sln
      parallel: true
      verbosity: minimal
    test: off
    after_build:
      - ps: >-
            $TestAndPublishWeb = "$env:APPVEYOR_BUILD_FOLDER\Scripts\TestAndPublishWeb.ps1"

            Write-Host $TestAndPublishWeb

            & "$TestAndPublishWeb"

  -
    matrix:
      only:
        - PRODUCT: android
    install:
      - ps: Install-Product node 12.18    
    build_script:
    - ps: >-
        $BuildAndPublishAndroid = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishAndroid.ps1"

        Write-Host $BuildAndPublishAndroid

        & "$BuildAndPublishAndroid"

  -
    matrix:
      only:
        - PRODUCT: ios
      fast_finish: true
    install:
      - sh: nvm install 12.18
    build_script: 
    - ps: >-
        $BuildAndPublishIOS = "$env:APPVEYOR_BUILD_FOLDER\Scripts\BuildAndPublishIOS.ps1"

        Write-Host $BuildAndPublishIOS

        & "$BuildAndPublishIOS"
        
deploy:
- provider: GitHub
  auth_token:
    secure: UhPMkdOfJ0iYk+ZEJapaimnlsy+yXWXYzwJ7Lgj9aiMq2lj5JcUkN1UI0Q9QZru6
  repository: IsraelHikingMap/Site
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
