version: 5.2.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    Install-Product node 6.10

    node -v

    npm install -g @angular/cli@1.4.4 --silent

before_build:
- ps: dotnet restore
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
after_test:
- ps: >-
    $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

    Write-Host $PostBuildTests

    & "$PostBuildTests"

    $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

    Write-Host $PostBuildPackArtifacts

    & "$PostBuildPackArtifacts"
