version: 5.2.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    Install-Product node 6.10

    node -v

    npm install -g npm@5.2.0 --loglevel=error

    npm install -g @angular/cli@1.5.5 --loglevel=error

before_build:
- ps: dotnet restore
build:
  project: IsraelHiking.sln
  parallel: true
  verbosity: minimal
after_test:
- ps: >-
    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    $PostBuildTests = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildTests.ps1"

    Write-Host $PostBuildTests

    & "$PostBuildTests"

    $PostBuildPackArtifacts = "$env:APPVEYOR_BUILD_FOLDER\Scripts\PostBuildPackArtifacts.ps1"

    Write-Host $PostBuildPackArtifacts

    & "$PostBuildPackArtifacts"
