version: '3.4'

services:
#  website:
#    image: israel-hiking
#    build: .
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./IsraelHiking.Web/appsettings.json:/israelhiking/appsettings.json
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  graphhopper:
    image: israelhikingmap/graphhopper:6.2
    container_name: graphhopper
    volumes:
      - ghdata:/data:rw
      - type: bind
        source: ./gh-config.yml
        target: /data/gh-config.yml
    ports:
      - 8989:8989
    entrypoint: ./graphhopper.sh --host 0.0.0.0 -i ignore.pbf -o /data/default-gh/ -c /data/gh-config.yml
    restart: always
  gpsbabel:
    image: israelhikingmap/gpsbabelwebapi
    container_name: gpsbabel
    ports:
      - 11987:80
    restart: always
  elevation:
    image: israelhikingmap/elevationwebapi
    container_name: elevation
    ports:
      - 11211:80
    restart: always
    volumes:
      - ./elevation-cache:/app/elevation-cache
  imagecreator:
    image: israelhikingmap/imagecreatorwebapi
    container_name: imagecreator
    ports:
      - 11311:80
    restart: always
volumes:
  esdata:
    driver: local
  ghdata:
    driver: local