version: '3.4'

services:
  #website:
  #  image: israel-hiking
  #  build: .
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #  ports:
  #    - "5000:5000"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  graphhopper:
    image: graphhopper/graphhopper
    container_name: graphhopper
    volumes:
      - ghdata:/data:rw
      - ./gh-config.yml:/data/gh-config.yml
    ports:
      - 8989:8989
    command: asia_israel-and-palestine.pbf -c /data/gh-config.yml -fd
    restart: always
volumes:
  esdata:
    driver: local
  ghdata:
    driver: local